//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.10 at 10:05:14 PM EET 
//


package com.features;

public enum Handle {

    WOODEN("wooden"),
    PLASTIC("plastic"),
    METAL("metal");
    private final String value;

    Handle(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Handle fromValue(String v) {
        for (Handle c : Handle.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
