//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.10 at 10:05:14 PM EET 
//


package com.features;

public enum Value {

    YES("yes"),
    NO("no");
    private final String value;

    Value(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Value fromValue(String v) {
        for (Value c : Value.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
