//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.10 at 10:05:14 PM EET 
//


package com.features;

public class Visual {

    protected int length;
    protected int width;
    protected Material material;
    protected Handle handle;
    protected String wood;
    protected Value value;
    protected Value drainage;

    /**
     * Gets the value of the length property.
     */
    public int getLength() {
        return length;
    }

    /**
     * Sets the value of the length property.
     */
    public void setLength(int value) {
        this.length = value;
    }

    /**
     * Gets the value of the width property.
     */
    public int getWidth() {
        return width;
    }

    /**
     * Sets the value of the width property.
     */
    public void setWidth(int value) {
        this.width = value;
    }

    /**
     * Gets the value of the material property.
     *
     * @return possible object is
     * {@link Material }
     */
    public Material getMaterial() {
        return material;
    }

    /**
     * Sets the value of the material property.
     *
     * @param value allowed object is
     *              {@link Material }
     */
    public void setMaterial(Material value) {
        this.material = value;
    }

    /**
     * Gets the value of the handle property.
     *
     * @return possible object is
     * {@link Handle }
     */
    public Handle getHandle() {
        return handle;
    }

    /**
     * Sets the value of the handle property.
     *
     * @param value allowed object is
     *              {@link Handle }
     */
    public void setHandle(Handle value) {
        this.handle = value;
    }

    /**
     * Gets the value of the wood property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getWood() {
        return wood;
    }

    /**
     * Sets the value of the wood property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setWood(String value) {
        this.wood = value;
    }

    /**
     * Gets the value of the value property.
     *
     * @return possible object is
     * {@link Value }
     */
    public Value getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     *
     * @param value allowed object is
     *              {@link Value }
     */
    public void setValue(Value value) {
        this.value = value;
    }

    /**
     * Gets the value of the drainage property.
     *
     * @return possible object is
     * {@link Value }
     */
    public Value getDrainage() {
        return drainage;
    }

    /**
     * Sets the value of the drainage property.
     *
     * @param value allowed object is
     *              {@link Value }
     */
    public void setDrainage(Value value) {
        this.drainage = value;
    }

}
